export const blogData = [
  {
    id: "1",
    title: "A Simple Step-by-Step Guide to Managing Your Lifestyle",
    description: "A detailed step by step guide to manage your lifestyle",
    category: "Lifestyle",
    image: "/images/blog1.png",
    createdAt: "2025-01-15",
    author: "Admin",
  },
  {
    id: "2",
    title: "Creating an Effective Startup Roadmap",
    description: "How to create an effective startup roadmap or ideas",
    category: "Startup",
    image: "/images/blog2.png",
    createdAt: "2025-01-20",
    author: "Admin",
  },
  {
    id: "3",
    title: "Learning New Tech to Boost Your Software Career",
    description: "Learning new technology to boost your career in software",
    category: "Technology",
    image: "/images/blog3.png",
    createdAt: "2025-01-25",
    author: "Admin",
  },
  {
    id: "4",
    title: "Tips for Getting the Most Out of Apps and Software",
    description: "Tips for getting the most out of apps and software",
    category: "Technology",
    image: "/images/blog4.png",
    createdAt: "2025-02-01",
    author: "Admin",
  },
  {
    id: "5",
    title: "Enhancing Your Skills and Capturing Memorable Moments",
    description: "Enhancing your skills and capturing memorable moments",
    category: "Lifestyle",
    image: "/images/blog5.png",
    createdAt: "2025-02-05",
    author: "Admin",
  },
  {
    id: "6",
    title: "Maximizing Returns by Minimizing Resources in Your Startup",
    description: "Maximizing returns by minimizing resources in your startup",
    category: "Startup",
    image: "/images/blog6.png",
    createdAt: "2025-02-10",
    author: "Admin",
  },
  {
    id: "7",
    title:
      "Luxury Home Taxes: Are They Fair, and What Do They Mean for the Market?",
    description: "Taxes on Luxury Houses",
    category: "Finance",
    image: "/images/blog7.png",
    createdAt: "2025-02-15",
    author: "Admin",
  },
  {
    id: "8",
    title: "The New Way of Study: Ditching the Old, Embracing the Now",
    description: "The New Way of Study",
    category: "Startup",
    image: "/images/blog8.png",
    createdAt: "2025-02-20",
    author: "Admin",
  },
  {
    id: "9",
    title: "Beyond Postcards: Why Tourism Matters More Than You Think",
    description: "Importance of Tourism",
    category: "Lifestyle",
    image: "/images/blog9.png",
    createdAt: "2025-02-25",
    author: "Admin",
  },
  {
    id: "10",
    title: "The Rise of Artificial Intelligence in Modern Technology",
    description: "AI is Everywhere: How Artificial Intelligence is Taking Over",
    category: "Technology",
    image: "/images/blog10.png",
    createdAt: "2025-03-01",
    author: "Admin",
  },
];
